### ISSUE TITLE
Block element glyph research

### ISSUE THREAD

**Issue by jublo** [source-foundry/meta#2]
Link to [Hack issue #159](https://github.com/chrissimpkins/Hack/issues/159)

- [X] Define Unicode code points for the box drawing glyphs
- [X] Define Unicode code points for block element glyphs
- [x] Determine Adobe automated generator tool support - is this for the block element glyphs or box drawing glyphs - ANSWER: this is for box drawing glyphs and is appropriate for v2.020, not this version
- [x] Determine common alignment patterns of the block element glyphs

**Comment by chrissimpkins** [comment]
Box drawing glyphs (`U+2500` to `U+257F`): 
- http://www.unicode.org/charts/beta/nameslist/c_2500.html
- http://www.unicode.org/charts/beta/nameslist/n_2500.html#2500

Block element glyphs (`U+2580` to `U+259F`):
- http://unicode.org/charts/PDF/U2580.pdf
- http://www.unicode.org/charts/beta/nameslist/c_2580.html
- http://www.unicode.org/charts/beta/nameslist/n_2580.html#2590

**Comment by chrissimpkins** [comment]
*Checklist item 3*:

The Adobe glyph generator tool is appropriate for v2.020 because it generates box drawing glyphs, not block element glyphs.

**Comment by chrissimpkins** [comment]
Here is where we are before changes with the block element and box drawing glyphs:

<img width="979" alt="box_and_line" src="https://cloud.githubusercontent.com/assets/4249591/11460981/971ac7a0-96c7-11e5-8bcf-e292183b0451.png">

The full block (U+2588) definitely has problems as previously reported.  I think that this is the one that npm is using.  Otherwise, on OS X seems to be relatively few alignment issues.  I will confirm that the widths and heights are as billed in the design.

The box drawing glyphs are a different story.  They look like they will require a bit more work.
